export const SET_USERS = "SET_USERS";
export const SEARCH_USER = "SEARCH_USER";
export const SORT_BY_NAME = "SORT_BY_NAME";
export const SHOW_LOWEST_RANKED = "SHOW_LOWEST_RANKED";
export const TOGGLE_FUZZY_SEARCH = "TOGGLE_FUZZY_SEARCH";
